export const customizableThemes = [
  {
    id: "custom",
    label: "Custom",
    preview: "gradient",
    settings: {
      wallpaperStyle: "fill",
      backgroundColor: "#000000",
      buttonColor: "#ffffff",
      buttonTextColor: "#000000",
      pageTextColor: "#ffffff",
      titleColor: "#ffffff",
      buttonStyle: "fill",
      cornerRoundness: "round",
      buttonShadow: "none",
      noise: false,
    }
  },
  {
    id: "agate",
    label: "Agate",
    preview: "gradient",
    settings: {
      wallpaperStyle: "gradient",
      backgroundColor: "#D4A574",
      gradientColor: "#8B4513",
      gradientDirection: "radial",
      buttonColor: "#8B4513",
      buttonTextColor: "#ffffff",
      pageTextColor: "#2C1810",
      titleColor: "#2C1810",
      buttonStyle: "fill",
      cornerRoundness: "rounder",
      buttonShadow: "soft",
      noise: true,
    }
  },
  {
    id: "neon-nights",
    label: "Neon Nights",
    preview: "gradient",
    settings: {
      wallpaperStyle: "gradient",
      backgroundColor: "#0a0015",
      gradientColor: "#1a0033",
      gradientDirection: "linear-down",
      buttonColor: "#ff00ff",
      buttonTextColor: "#ffffff",
      pageTextColor: "#00ffff",
      titleColor: "#ff00ff",
      buttonStyle: "outline",
      cornerRoundness: "round",
      buttonShadow: "hard",
      noise: false,
    }
  },
  {
    id: "cyberpunk",
    label: "Cyberpunk",
    preview: "pattern",
    settings: {
      wallpaperStyle: "pattern",
      backgroundColor: "#0d1117",
      pattern: "matrix",
      gradientColor: "#00ff41",
      buttonColor: "#00ff41",
      buttonTextColor: "#0d1117",
      pageTextColor: "#00ff41",
      titleColor: "#00ff41",
      buttonStyle: "fill",
      cornerRoundness: "square",
      buttonShadow: "hard",
      noise: true,
    }
  },
  {
    id: "ocean-wave",
    label: "Ocean Wave",
    preview: "gradient",
    settings: {
      wallpaperStyle: "gradient",
      backgroundColor: "#0077BE",
      gradientColor: "#00C9A7",
      gradientDirection: "linear-down",
      buttonColor: "rgba(255, 255, 255, 0.2)",
      buttonTextColor: "#ffffff",
      pageTextColor: "#ffffff",
      titleColor: "#ffffff",
      buttonStyle: "glass",
      cornerRoundness: "full",
      buttonShadow: "soft",
      noise: false,
    }
  },
  {
    id: "sunset-glow",
    label: "Sunset Glow",
    preview: "gradient",
    settings: {
      wallpaperStyle: "gradient",
      backgroundColor: "#FF6B6B",
      gradientColor: "#FFE66D",
      gradientDirection: "radial",
      buttonColor: "#ffffff",
      buttonTextColor: "#FF6B6B",
      pageTextColor: "#ffffff",
      titleColor: "#ffffff",
      buttonStyle: "fill",
      cornerRoundness: "full",
      buttonShadow: "strong",
      noise: false,
    }
  },
  {
    id: "aurora",
    label: "Aurora",
    preview: "gradient",
    settings: {
      wallpaperStyle: "gradient",
      backgroundColor: "#1a103d",
      gradientColor: "#a855f7",
      gradientDirection: "linear-down",
      buttonColor: "rgba(168, 85, 247, 0.3)",
      buttonTextColor: "#ffffff",
      pageTextColor: "#e9d5ff",
      titleColor: "#ffffff",
      buttonStyle: "glass",
      cornerRoundness: "rounder",
      buttonShadow: "soft",
      noise: true,
    }
  },
  {
    id: "geometric",
    label: "Geometric",
    preview: "pattern",
    settings: {
      wallpaperStyle: "pattern",
      backgroundColor: "#1e293b",
      pattern: "grid",
      gradientColor: "#38bdf8",
      buttonColor: "#38bdf8",
      buttonTextColor: "#1e293b",
      pageTextColor: "#f1f5f9",
      titleColor: "#ffffff",
      buttonStyle: "fill",
      cornerRoundness: "round",
      buttonShadow: "none",
      noise: false,
    }
  },
];

export const videoThemes = [
  {
    id: "floating-bubbles",
    label: "Floating Bubbles",
    preview: "video",
    videoUrl: "https://cdn.pixabay.com/video/2022/11/07/138197-769264329_large.mp4",
    settings: {
      wallpaperStyle: "video",
      backgroundVideo: "https://cdn.pixabay.com/video/2022/11/07/138197-769264329_large.mp4",
      backgroundColor: "#1a1a2e",
      buttonColor: "rgba(255, 255, 255, 0.25)",
      buttonTextColor: "#ffffff",
      pageTextColor: "#ffffff",
      titleColor: "#ffffff",
      buttonStyle: "glass",
      cornerRoundness: "full",
      buttonShadow: "soft",
      noise: false,
    }
  },
  {
    id: "cosmic-waves",
    label: "Cosmic Waves",
    preview: "video",
    videoUrl: "https://cdn.pixabay.com/video/2021/08/03/84380-586636620_large.mp4",
    settings: {
      wallpaperStyle: "video",
      backgroundVideo: "https://cdn.pixabay.com/video/2021/08/03/84380-586636620_large.mp4",
      backgroundColor: "#000000",
      buttonColor: "rgba(147, 51, 234, 0.4)",
      buttonTextColor: "#ffffff",
      pageTextColor: "#e9d5ff",
      titleColor: "#ffffff",
      buttonStyle: "glass",
      cornerRoundness: "rounder",
      buttonShadow: "hard",
      noise: false,
    }
  },
  {
    id: "fire-particles",
    label: "Fire Particles",
    preview: "video",
    videoUrl: "https://cdn.pixabay.com/video/2022/05/04/116526-706004937_large.mp4",
    settings: {
      wallpaperStyle: "video",
      backgroundVideo: "https://cdn.pixabay.com/video/2022/05/04/116526-706004937_large.mp4",
      backgroundColor: "#1a0000",
      buttonColor: "rgba(255, 87, 51, 0.3)",
      buttonTextColor: "#ffffff",
      pageTextColor: "#fecaca",
      titleColor: "#ffffff",
      buttonStyle: "glass",
      cornerRoundness: "full",
      buttonShadow: "hard",
      noise: false,
    }
  },
  {
    id: "northern-lights",
    label: "Northern Lights",
    preview: "video",
    videoUrl: "https://cdn.pixabay.com/video/2022/12/05/142608-778946634_large.mp4",
    settings: {
      wallpaperStyle: "video",
      backgroundVideo: "https://cdn.pixabay.com/video/2022/12/05/142608-778946634_large.mp4",
      backgroundColor: "#0a192f",
      buttonColor: "rgba(134, 239, 172, 0.25)",
      buttonTextColor: "#ffffff",
      pageTextColor: "#d1fae5",
      titleColor: "#ffffff",
      buttonStyle: "glass",
      cornerRoundness: "rounder",
      buttonShadow: "soft",
      noise: false,
    }
  },
  {
    id: "neon-grid",
    label: "Neon Grid",
    preview: "video",
    videoUrl: "https://cdn.pixabay.com/video/2022/01/18/104988-667500758_large.mp4",
    settings: {
      wallpaperStyle: "video",
      backgroundVideo: "https://cdn.pixabay.com/video/2022/01/18/104988-667500758_large.mp4",
      backgroundColor: "#000000",
      buttonColor: "rgba(236, 72, 153, 0.3)",
      buttonTextColor: "#ffffff",
      pageTextColor: "#fce7f3",
      titleColor: "#ec4899",
      buttonStyle: "glass",
      cornerRoundness: "round",
      buttonShadow: "hard",
      noise: true,
    }
  },
  {
    id: "liquid-gold",
    label: "Liquid Gold",
    preview: "video",
    videoUrl: "https://cdn.pixabay.com/video/2021/07/23/82747-578896226_large.mp4",
    settings: {
      wallpaperStyle: "video",
      backgroundVideo: "https://cdn.pixabay.com/video/2021/07/23/82747-578896226_large.mp4",
      backgroundColor: "#1a1100",
      buttonColor: "rgba(251, 191, 36, 0.3)",
      buttonTextColor: "#ffffff",
      pageTextColor: "#fef3c7",
      titleColor: "#fbbf24",
      buttonStyle: "glass",
      cornerRoundness: "full",
      buttonShadow: "strong",
      noise: false,
    }
  },
];

export const advancedThemes = [
  {
    id: "holographic",
    label: "Holographic",
    preview: "pattern",
    settings: {
      wallpaperStyle: "pattern",
      backgroundColor: "#0a0a0a",
      pattern: "morph",
      gradientColor: "#a855f7",
      buttonColor: "rgba(168, 85, 247, 0.2)",
      buttonTextColor: "#ffffff",
      pageTextColor: "#e9d5ff",
      titleColor: "#a855f7",
      buttonStyle: "glass",
      cornerRoundness: "rounder",
      buttonShadow: "hard",
      noise: true,
    }
  },
  {
    id: "retro-wave",
    label: "Retro Wave",
    preview: "gradient",
    settings: {
      wallpaperStyle: "gradient",
      backgroundColor: "#2d1b69",
      gradientColor: "#f72585",
      gradientDirection: "linear-down",
      buttonColor: "#00f5ff",
      buttonTextColor: "#2d1b69",
      pageTextColor: "#ffd60a",
      titleColor: "#ffd60a",
      buttonStyle: "fill",
      cornerRoundness: "square",
      buttonShadow: "hard",
      noise: true,
    }
  },
  {
    id: "frosted-glass",
    label: "Frosted Glass",
    preview: "blur",
    settings: {
      wallpaperStyle: "blur",
      backgroundColor: "#e0f2fe",
      buttonColor: "rgba(255, 255, 255, 0.3)",
      buttonTextColor: "#0369a1",
      pageTextColor: "#0c4a6e",
      titleColor: "#0c4a6e",
      buttonStyle: "glass",
      cornerRoundness: "rounder",
      buttonShadow: "soft",
      noise: false,
    }
  },
  {
    id: "matrix-code",
    label: "Matrix Code",
    preview: "pattern",
    settings: {
      wallpaperStyle: "pattern",
      backgroundColor: "#000000",
      pattern: "matrix",
      gradientColor: "#00ff00",
      buttonColor: "rgba(0, 255, 0, 0.2)",
      buttonTextColor: "#00ff00",
      pageTextColor: "#00ff00",
      titleColor: "#00ff00",
      buttonStyle: "outline",
      cornerRoundness: "square",
      buttonShadow: "hard",
      noise: true,
    }
  },
  {
    id: "organic-flow",
    label: "Organic Flow",
    preview: "pattern",
    settings: {
      wallpaperStyle: "pattern",
      backgroundColor: "#1e1b4b",
      pattern: "organic",
      gradientColor: "#8b5cf6",
      buttonColor: "rgba(139, 92, 246, 0.3)",
      buttonTextColor: "#ffffff",
      pageTextColor: "#ddd6fe",
      titleColor: "#c4b5fd",
      buttonStyle: "glass",
      cornerRoundness: "full",
      buttonShadow: "soft",
      noise: false,
    }
  },
  {
    id: "cherry-blossom",
    label: "Cherry Blossom",
    preview: "gradient",
    settings: {
      wallpaperStyle: "gradient",
      backgroundColor: "#fce7f3",
      gradientColor: "#ec4899",
      gradientDirection: "radial",
      buttonColor: "#be185d",
      buttonTextColor: "#ffffff",
      pageTextColor: "#831843",
      titleColor: "#9f1239",
      buttonStyle: "fill",
      cornerRoundness: "full",
      buttonShadow: "soft",
      noise: false,
    }
  },
  {
    id: "midnight-city",
    label: "Midnight City",
    preview: "gradient",
    settings: {
      wallpaperStyle: "gradient",
      backgroundColor: "#0f172a",
      gradientColor: "#1e293b",
      gradientDirection: "linear-down",
      buttonColor: "#38bdf8",
      buttonTextColor: "#0f172a",
      pageTextColor: "#cbd5e1",
      titleColor: "#38bdf8",
      buttonStyle: "fill",
      cornerRoundness: "round",
      buttonShadow: "hard",
      noise: true,
    }
  },
  {
    id: "tropical-paradise",
    label: "Tropical Paradise",
    preview: "gradient",
    settings: {
      wallpaperStyle: "gradient",
      backgroundColor: "#064e3b",
      gradientColor: "#10b981",
      gradientDirection: "radial",
      buttonColor: "#fbbf24",
      buttonTextColor: "#064e3b",
      pageTextColor: "#d1fae5",
      titleColor: "#fef3c7",
      buttonStyle: "fill",
      cornerRoundness: "rounder",
      buttonShadow: "strong",
      noise: false,
    }
  },
];