export const fonts = [
  { name: "Albert Sans", isPro: false },
  { name: "Belanosima", isPro: true },
  { name: "Bricolage Grotesque", isPro: true, proLevel: 4 },
  { name: "DM Sans", isPro: false },
  { name: "Epilogue", isPro: false },
  { name: "IBM Plex Sans", isPro: false },
  { name: "Inter", isPro: false },
  { name: "Lato", isPro: true },
  { name: "Link Sans", isPro: false },
  { name: "M Plus Rounded", isPro: true },
  { name: "Manrope", isPro: false },
  { name: "Oxanium", isPro: false },
  { name: "Poppins", isPro: true, proLevel: 4 },
  { name: "Red Hat Display", isPro: false },
  { name: "Roboto", isPro: true, proLevel: 4 },
  { name: "Rubik", isPro: true },
  { name: "Space Grotesk", isPro: true, proLevel: 4 },
  { name: "Syne", isPro: true },
];